
[window]
dimensions = {columns = 90, lines = 24}
decorations = "Full"
opacity = 0.85

[scrolling]
multiplier = 5

[font]
normal = {family = "Meslo LGS Nerd Font", style = "Regular" }
size = 11

[terminal]
osc52 = "CopyPaste"

[general]
import = [ "~/.config/alacritty/themes/alabaster_dark.toml"]
#import = [ "~/.config/alacritty/themes/alabaster.toml"]
#import = [ "~/.config/alacritty/themes/catppuccin_mocha.toml"]
#import = [ "~/.config/alacritty/themes/iterm.toml"]
#import = [ "~/.config/alacritty/themes/vscode.toml"]
